//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoChangeLockScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoChangeLockScreen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Change.
        /// </summary>
        public static string AutoChange {
            get {
                return ResourceManager.GetString("AutoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing News.
        /// </summary>
        public static string BingNews {
            get {
                return ResourceManager.GetString("BingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1982.
        /// </summary>
        public static string BirdYear {
            get {
                return ResourceManager.GetString("BirdYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mid-news.com.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy App.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Source.
        /// </summary>
        public static string ChooseSource {
            get {
                return ResourceManager.GetString("ChooseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background cant be updated as you clicked no!!.
        /// </summary>
        public static string ClickNo {
            get {
                return ResourceManager.GetString("ClickNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed downloading..
        /// </summary>
        public static string CompletedDownloading {
            get {
                return ResourceManager.GetString("CompletedDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Images.
        /// </summary>
        public static string DefaultImages {
            get {
                return ResourceManager.GetString("DefaultImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.... please wait....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lttrungbk@yahoo.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email this.
        /// </summary>
        public static string EmailThis {
            get {
                return ResourceManager.GetString("EmailThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate MyApp.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear that you didn&apos;t want to rate this app. Tell us about your experience or suggest how we can make it better..
        /// </summary>
        public static string FeedBackMsg {
            get {
                return ResourceManager.GetString("FeedBackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyApp Customer Feedback .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@myapp.com.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your tag of images you want to show at lock screen from Flicker..
        /// </summary>
        public static string FlickerIntro {
            get {
                return ResourceManager.GetString("FlickerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google News.
        /// </summary>
        public static string GoogleNews {
            get {
                return ResourceManager.GetString("GoogleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string HalfDay {
            get {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow these steps: /// 
        ///1. Select &quot;Default&quot; button
        ///2. You will see the default images
        ///3. Press Start Button to start set wallpaper with the first image
        ///4. Choose &quot;Yes&quot; if the App request your permission..
        /// </summary>
        public static string HelpDefault {
            get {
                return ResourceManager.GetString("HelpDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Touch Your photos
        /// ///2. Touch Add Button to download images
        ///3. Write your tag you want to download
        /// ///4. Touch Show images to see images
        /// ///5. Touch Download to download images
        ///6. Touch Finished button when downloading is finished
        ///7. Select images and press Remove if you want to remove images
        ///8. Click start button to start
        /// ///9. Click Yes when being requested.
        /// </summary>
        public static string HelpRss {
            get {
                return ResourceManager.GetString("HelpRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Touch Your photos
        /// ///2. Touch Add Button to add new Image
        ///3. Select from library or take a picture
        /// ///4. Crop as you want
        /// ///5. Repeat with others images
        /// ///6. Select images and press Remove if you want to remove images
        ///7. Touchstart button to start
        /// ///8. Touch Yes when being requested.
        /// </summary>
        public static string HelpYours {
            get {
                return ResourceManager.GetString("HelpYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Source.
        /// </summary>
        public static string ImageSource {
            get {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks so much for your supports. If you like this app, Rate it 5 stars and recomment other to use it. If you have any suggestion, send it to lttrungbk@yahoo.com. Thanks!.
        /// </summary>
        public static string IntroMySelf {
            get {
                return ResourceManager.GetString("IntroMySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Images.
        /// </summary>
        public static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen changed. Go to lock screen..
        /// </summary>
        public static string LockScreenChanged {
            get {
                return ResourceManager.GetString("LockScreenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Apps.
        /// </summary>
        public static string MyApps {
            get {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Facebook.
        /// </summary>
        public static string myfacebook {
            get {
                return ResourceManager.GetString("myfacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Thanh Trung.
        /// </summary>
        public static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string NewsSource {
            get {
                return ResourceManager.GetString("NewsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image found for tag.
        /// </summary>
        public static string NoImageFoundForTag {
            get {
                return ResourceManager.GetString("NoImageFoundForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network is available...
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of images.
        /// </summary>
        public static string NumberOfImages {
            get {
                return ResourceManager.GetString("NumberOfImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try other tag name for image..
        /// </summary>
        public static string PleaseTryOtherTag {
            get {
                return ResourceManager.GetString("PleaseTryOtherTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your tag in textbox of images you want to show on lock screen.
        /// </summary>
        public static string PleaseWriteTag {
            get {
                return ResourceManager.GetString("PleaseWriteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate It.
        /// </summary>
        public static string RateIt {
            get {
                return ResourceManager.GetString("RateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying MyApp?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Source.
        /// </summary>
        public static string SetSource {
            get {
                return ResourceManager.GetString("SetSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this.
        /// </summary>
        public static string ShareThis {
            get {
                return ResourceManager.GetString("ShareThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Images.
        /// </summary>
        public static string ShowImages {
            get {
                return ResourceManager.GetString("ShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 minutes.
        /// </summary>
        public static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS this.
        /// </summary>
        public static string SMSThis {
            get {
                return ResourceManager.GetString("SMSThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string Thirdty {
            get {
                return ResourceManager.GetString("Thirdty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string TwoHours {
            get {
                return ResourceManager.GetString("TwoHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Photos.
        /// </summary>
        public static string YourPhotos {
            get {
                return ResourceManager.GetString("YourPhotos", resourceCulture);
            }
        }
    }
}
