//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoChangeLockScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoChangeLockScreen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Change.
        /// </summary>
        public static string AutoChange {
            get {
                return ResourceManager.GetString("AutoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy App.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Source.
        /// </summary>
        public static string ChooseSource {
            get {
                return ResourceManager.GetString("ChooseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Images.
        /// </summary>
        public static string DefaultImages {
            get {
                return ResourceManager.GetString("DefaultImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow these steps: /// 
        ///1. Select &quot;Default&quot; button
        ///2. You will see the default images
        ///3. Press Start Button to start set wallpaper with the first image
        ///4. Choose &quot;Yes&quot; if the App request your permission..
        /// </summary>
        public static string HelpDefault {
            get {
                return ResourceManager.GetString("HelpDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Chon nut Your photos ///2. Chon nut Add de them photo ///3. Chon photo tu thu vien hoac chup anh ///4. Crop anh theo y muon ///5. Lap lai voi nhung anh khac neu ban muon them ///6. Chon anh neu ban muon xoa bot va nhan nut xoa ///7. nhan nut start de bat dau ///8. Chon Yes khi duoc hoi.
        /// </summary>
        public static string HelpRss {
            get {
                return ResourceManager.GetString("HelpRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Chon nut Your photos ///2. Chon nut Add de them photo ///3. Chon photo tu thu vien hoac chup anh ///4. Crop anh theo y muon ///5. Lap lai voi nhung anh khac neu ban muon them ///6. Chon anh neu ban muon xoa bot va nhan nut xoa ///7. nhan nut start de bat dau ///8. Chon Yes khi duoc hoi.
        /// </summary>
        public static string HelpYours {
            get {
                return ResourceManager.GetString("HelpYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Source.
        /// </summary>
        public static string ImageSource {
            get {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval time.
        /// </summary>
        public static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Images.
        /// </summary>
        public static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Apps.
        /// </summary>
        public static string MyApps {
            get {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate It.
        /// </summary>
        public static string RateIt {
            get {
                return ResourceManager.GetString("RateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Source.
        /// </summary>
        public static string SetSource {
            get {
                return ResourceManager.GetString("SetSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Photos.
        /// </summary>
        public static string YourPhotos {
            get {
                return ResourceManager.GetString("YourPhotos", resourceCulture);
            }
        }
    }
}
